import { NextResponse } from 'next/server';
import { createServerClient, createAdminClient } from '@ababil/supabase';
import { cookies } from 'next/headers';

function getAdminClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
  return createAdminClient(url, key);
}

// GET /api/agent/rfq/[id] — Retrieve single RFQ with quotes
export async function GET(
  req: Request,
  { params }: { params: { id: string } }
) {
  try {
    const { id: rfqId } = params;

    const cookieStore = cookies();
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
    const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
    const supabase = createServerClient(supabaseUrl, supabaseAnonKey, cookieStore);
    const supabaseAdmin = getAdminClient();

    let user: any = null;

    // Support Telegram Bot auth
    const telegramChatId = req.headers.get('x-telegram-chat-id');
    const telegramBotToken = req.headers.get('x-telegram-bot-token');

    if (telegramChatId && telegramBotToken && telegramBotToken === process.env.TELEGRAM_BOT_TOKEN) {
      const { data: profile } = await supabaseAdmin
        .from('profiles')
        .select('id')
        .eq('telegram_chat_id', String(telegramChatId))
        .single();
      
      if (profile) {
        user = { id: profile.id };
      }
    } else {
      const { data: { user: authUser } } = await supabase.auth.getUser();
      user = authUser;
    }

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { data: rfq, error } = await supabaseAdmin
      .from('rfqs')
      .select(`
        id, title, description, rfq_type, category, quantity, budget_usdc,
        delivery_deadline, location, requirements, status, created_at, updated_at,
        buyer_id,
        vendor_quotes(
          id, unit_price_usdc, total_price_usdc, delivery_days, notes,
          auto_generated, status, escrow_status, escrow_locked_at, created_at,
          vendors(id, name, slug, logo_url, rating, verified)
        )
      `)
      .eq('id', rfqId)
      .single();

    if (error || !rfq) {
      return NextResponse.json({ success: false, error: 'RFQ not found' }, { status: 404 });
    }

    // Verify buyer ownership or vendor role
    // For now we restrict this GET endpoint to the buyer who created it
    if (rfq.buyer_id !== user.id) {
      // Check if user is a vendor who is allowed to view quotes (e.g. their own quote, or if they have permission)
      // For buyer convenience, we restrict to the buyer
      return NextResponse.json({ success: false, error: 'Access denied' }, { status: 403 });
    }

    // Map quotes
    const quotes = ((rfq.vendor_quotes as any[]) ?? [])
      .map((q) => ({
        id: q.id,
        vendorId: q.vendors?.id,
        vendorName: q.vendors?.name,
        vendorSlug: q.vendors?.slug,
        vendorLogoUrl: q.vendors?.logo_url,
        vendorRating: parseFloat(q.vendors?.rating ?? '0'),
        vendorVerified: q.vendors?.verified ?? false,
        unitPriceUsdc: parseFloat(q.unit_price_usdc),
        totalPriceUsdc: parseFloat(q.total_price_usdc),
        deliveryDays: q.delivery_days,
        notes: q.notes,
        autoGenerated: q.auto_generated,
        status: q.status,
        escrowStatus: q.escrow_status,
        escrowLockedAt: q.escrow_locked_at,
        submittedAt: q.created_at,
      }));

    const rfqDetails = {
      id: rfq.id,
      title: rfq.title,
      description: rfq.description,
      rfqType: rfq.rfq_type,
      category: rfq.category,
      quantity: rfq.quantity,
      budgetUsdc: parseFloat(rfq.budget_usdc),
      deliveryDeadline: rfq.delivery_deadline,
      location: rfq.location,
      requirements: rfq.requirements,
      status: rfq.status,
      createdAt: rfq.created_at,
      updatedAt: rfq.updated_at,
      quotes,
    };

    return NextResponse.json({ success: true, rfq: rfqDetails });
  } catch (err: any) {
    console.error('Error fetching RFQ detail:', err);
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
